<?php echo $this->docType(); ?>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<?php 
		echo $this->headTitle();
		echo $this->headMeta();
		?>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="">
		<meta name="author" content="">

		<!-- Le styles -->
		<?php 
		$this->headLink()->appendStylesheet( $this->baseUrl() . '/assets/css/bootstrap.css')
						 ->appendStylesheet( $this->baseUrl() . '/assets/css/bootstrap-responsive.css')
						 ->appendStylesheet( $this->baseUrl() . '/assets/css/style.css');
		
		echo $this->headLink();
		?>
		<style type="text/css">
			body {
				padding-top: 60px;
				padding-bottom: 40px;
			}
			.sidebar-nav {
				padding: 9px 0;
			}
		</style>

		<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->

		<!-- Le fav and touch icons -->
		<link rel="shortcut icon" href="assets/ico/favicon.ico">
		<link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?php $this->baseUrl() ?>/assets/ico/apple-touch-icon-144-precomposed.png">
		<link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?php $this->baseUrl() ?>/assets/ico/apple-touch-icon-114-precomposed.png">
		<link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?php $this->baseUrl() ?>/assets/ico/apple-touch-icon-72-precomposed.png">
		<link rel="apple-touch-icon-precomposed" href="<?php $this->baseUrl() ?>/assets/ico/apple-touch-icon-57-precomposed.png">
	</head>

	<body>

		<div id="topbar" class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<?php echo $this->render('top-nav.phtml'); ?>
			</div>
		</div><!-- /topbar -->

		<div class="container-fluid">
			<div class="row-fluid">
				<!-- Navigation -->
				<div id="navigation" class="span2">
					<div class="well sidebar-nav">
						<?php echo $this->render('side-nav.phtml'); ?>
					</div><!--/.well -->
				</div><!--/#navigation-->

				<!-- Content -->
				<div id="content" class="span10">
					<div class="row-fluid">
						<?php echo $this->layout()->content; ?>
					</div>
				</div><!--/#content-->
			</div><!--/row-->

			<hr>

			<footer>
				<p>&copy; Company 2012</p>
			</footer>

		</div><!--/.fluid-container-->

		<!-- Le javascript
		================================================== -->
		<!-- Placed at the end of the document so the pages load faster -->
		<?php 
		$this->jQuery()->setLocalPath( $this->baseUrl().'/assets/js/jquery.js' ) // CDN: setVersion('1.7.1')
				   	   ->addJavascriptFile( $this->baseUrl() . '/assets/js/bootstrap-transitionn.js' )
				   	   ->addJavascriptFile( $this->baseUrl() . '/assets/js/bootstrap-alert.js' )
				   	   ->addJavascriptFile( $this->baseUrl() . '/assets/js/bootstrap-modal.js' )
				   	   ->addJavascriptFile( $this->baseUrl() . '/assets/js/bootstrap-dropdown.js' )
				   	   ->addJavascriptFile( $this->baseUrl() . '/assets/js/bootstrap-scrollspy.js' )
				   	   ->addJavascriptFile( $this->baseUrl() . '/assets/js/bootstrap-tab.js' )
				   	   ->addJavascriptFile( $this->baseUrl() . '/assets/js/bootstrap-tooltip.js' )
				   	   ->addJavascriptFile( $this->baseUrl() . '/assets/js/bootstrap-popover.js' )
				   	   ->addJavascriptFile( $this->baseUrl() . '/assets/js/bootstrap-button.js' )
				   	   ->addJavascriptFile( $this->baseUrl() . '/assets/js/bootstrap-collapse.js' )
				   	   ->addJavascriptFile( $this->baseUrl() . '/assets/js/bootstrap-carousel.js' )
				   	   ->addJavascriptFile( $this->baseUrl() . '/assets/js/bootstrap-typeahead.js' )
					   // jQuery-UI
	           		   ->setUiLocalPath($this->baseUrl(). '/js/jquery-ui/jquery-ui-1.8.18.custom.min.js') // CDN: setUiVersion('1.8.18')
	           		   ->addStylesheet($this->baseUrl(). '/js/jquery-ui/css/smoothness/jquery-ui-1.8.21.custom.css')
				  	   ->uiEnable();
		$this->jQuery()->addOnLoad('
			$("#ajax-loader").ajaxStart(function(){
				$(this).show();
			}).ajaxStop(function(){
				$(this).hide();
			});
			
			$(".btn-group").tooltip({
				selector: "a[rel=tooltip]"
			});
			
			//Update Message popup
			jQuery.fn.center = function () {
				this.animate({"top":( jQuery(window).height() - this.height() - 150 ) / 2+jQuery(window).scrollTop() + "px"},100);
				this.css( "left", 700 );
				return this;
			}
			
			jQuery( "#ajax-message" ).center();
			jQuery( "#ajax-loader" ).center();
			
			jQuery(window).scroll(function() {
				jQuery( "#ajax-message" ).center();
				jQuery( "#ajax-loader" ).center();
			});
		');
		echo $this->jQuery();
		?>
	</body>
</html>
