<?php 
$this->jQuery()->addJavascriptFile( $this->baseUrl() . '/js/front/page.js' );
?>

<!--
--- Ajax request, tampilkan detail
-->
<?php if( $this->isXmlHttpRequest ) : ?>
	<h1 class="title bdr-btm">
		<?php echo $this->page->content_name ?>
	</h1>
	<p>
		<?php echo $this->page->content_description; ?>
	</p>
	<?php if( $this->page->hasChild() && $this->page->content_parent != 0 ) : ?>
		<?php foreach( $this->page->getChild() as $child ) : ?>
			<div class="txt">
				<h2><?php echo $child->content_name ?></h2>
				<?php 
				$link = '...<a href="'.$this->url(array('name' => $child->content_slug), 'people').'" title="Detail '.$this->page->content_name.'">Read more</a>';
				echo $this->getExcerptContent($child->content_description, $link, false); 
				?>
			</div>
		<?php endforeach; ?>
	<?php endif; ?>
<?php else : ?>
	<?php if( $this->page->hasChild() && $this->page->content_parent == 0 ) : ?>
		<div class="page-left">
			<ul id="nav-left" class="about">
				<li class="active">
					<a href="javascript:void(0)" id="<?php echo $this->page->content_slug; ?>">
						<?php echo $this->page->content_name; ?>
					</a>
				</li>
				<?php foreach( $this->pages as $p ) : ?>
				<li>
					<a href="javascript:void(0)" id="<?php echo $p->content_slug; ?>"><?php echo $p->content_name; ?></a>
				</li>
				<?php endforeach; ?>
			</ul>
		</div>
		<div class="page-right" id="response">
			<h1 class="title bdr-btm"><?php echo $this->page->content_name ?></h1>
			<p>
				<?php echo $this->page->content_description; ?>
			</p>
		</div>
	<?php else : ?>
		<div class="page-full">
			<h1 class="title bdr-btm"><?php echo $this->page->content_name ?></h1>
			<?php echo $this->page->content_description; ?>
			<?php if( $this->page->hasChild() && $this->page->content_parent != 0 ) : ?>
				<?php foreach( $this->page->getChild() as $child ) : ?>
					<div class="txt">
						<h2><?php echo $child->content_name ?></h2>
						<?php 
						if( $child->content_type == 'people' )
						{
							$link = '...<a href="'.$this->url(array('name' => $child->content_slug), 'people').'" title="Detail '.$child->content_name.'">Read more</a>';
							echo $this->getExcerptContent($child->content_description, $link, false); 
						} else {
							echo $child->content_description; 
						}
						
						?>
					</div>
				<?php endforeach; ?>
			<?php endif; ?>
		</div>
	<?php endif; ?>
<?php endif; ?>
