<div class="portlet">
	<div class="portlet-header">
		<h3><?php echo $this->title ?></h3>
	</div>
	<div class="portlet-inside">
		<?php echo $this->formLabel($this->element->getName(), 
                         $this->element->getLabel()) ?>
		<?php echo  $this->{$this->element->helper}(
		$this->element->getName(),
		$this->element->getValue(),
		$this->element->getAttribs()
		) ?>
		<p class="help-block"><?php echo $this->element->getDescription() ?></p>
	</div>
</div>
