<?php 
$this->jQuery()->addJavascriptFile($this->baseUrl() . '/js/jquery.nested.sortable.js') 
			   ->addJavascriptFile($this->baseUrl() . '/js/admin/menus.js')
			   ->addOnLoad("
				   TheMenus.ajaxurl = '".$this->baseUrl(false)."/admin/ajax/menu';
				   TheMenus.init();
			   ");
// value
$primary_menu = $this->getOptions('primary_menu'); // primary menu
$top_menu = $this->getOptions('top_menu'); // top menu

// navigation menu	
$navigationMenu = new Zend_Form_Element_Select('menu');
$navigationMenu->addMultiOption('', '-- Select Menu --')
			   ->setAttribs(array('class' => 'select-menu half'))
			   ->setDecorators(array(
				   'ViewHelper',
				   array('Label', array('class' => 'control-label alignleft small'))
				));
// available menu	
$availableMenu = new Zend_Form_Element_Select('available-menu');
$availableMenu->setLabel('Menu')
			  ->addMultiOption('', '-- Select Menu --')
			  ->setAttribs(array('class' => 'select-menu'))
			  ->setDecorators(array(
					'ViewHelper', 
					array( 'Label', array('class' => 'control-label alignleft quarter') ),
					array( 'HtmlTag', array('tag' => 'div', 'class' => 'control-group') )
				));
// get menus
$menus = $this->getMenus();
if( $menus ){
	foreach( $menus as $key => $menu )
	{
		$navigationMenu->addMultiOption($key, ucwords($menu['name']));
		$availableMenu->addMultiOption($key, ucwords($menu['name']));
	}
}
// set value
$availableMenu->setValue($this->current_menu);
?>
			   
<h2>Menus</h2>
	
<div id="custom-pages" class="span4 alpha">

	<!------------------
	---- NAVIGATION ----
	-------------------->
	<div id="navigation" class="portlet">
		<div class="portlet-header">
			<h4>Navigation</h4>
		</div>
		<div class="portlet-inside" style="display: block;">
			<div class="alert alert-info portlet-message">
				<i class="icon-exclamation-sign"></i> Select which menu you would like to use.
			</div>
			<div class="portlet-form">
				<form action="#" class="navigation form-horizontal">
					<div class="control-group">
						<?php echo $navigationMenu->setLabel('Top')->setValue($top_menu);
						?><img class="ajax-loader-widget" src="<?php echo $this->baseUrl() ?>/images/ajax_spin.gif"/>
						<input type="hidden" name="navigation" value="top_menu" />
						<input type="submit" class="btn btn-primary" value="Save" />
					</div>
				</form>
				<form action="#" class="navigation form-horizontal">
					<div class="control-group">
						<?php echo $navigationMenu->setLabel('Primary')->setValue($primary_menu);
						?><img class="ajax-loader-widget" src="<?php echo $this->baseUrl() ?>/images/ajax_spin.gif"/>
						<input type="hidden" name="navigation" value="primary_menu" />
						<input type="submit" class="btn btn-primary" value="Save" />
					</div>
				</form>
			</div>
		</div>
	</div>

	<!-------------------
	---- CUSTOM LINKS ---
	-------------------->
	<div id="pages-link" class="portlet">
		<div class="portlet-header">
			<h4>Custom Links</h4>
		</div>
		<div class="portlet-inside" style="display: block;">
			<div class="portlet-form">
				<form action="#" class="form-horizontal">
					<?php echo $availableMenu;
					?>
					<div class="control-group">
						<label class="control-label alignleft quarter">URL</label>
						<input type="text" name="url" value="http://" />
					</div>
					<div class="control-group">
						<label class="control-label alignleft quarter">Label</label>
						<input type="text" name="label" placeholder="label" />
					</div>
					<div class="right">
						<img class="ajax-loader-widget" src="<?php echo $this->baseUrl() ?>/images/ajax_spin.gif"/>
						<input type="submit" class="add-page-link btn btn-primary" value="Add Item" />
					</div>
				</form>
			</div>
		</div>
	</div>

	<!-------------
	---- PAGES ----
	-------------->
	<div id="pages-list" class="portlet">
		<div class="portlet-header">
			<h4>Pages</h4>
		</div>
		<div class="portlet-inside" style="display: block;">
			<div class="portlet-form">
				<form action="#" id="form-page" class="form-horizontal">
					<?php echo $availableMenu;
					?>
					<label>Select Page :</label>
					<?php foreach( $this->pages as $page ) :  $_pages[$page->getId()] = $page; // buat array _pages untuk render menu
					?>
					<label class="checkbox">
						<input type="checkbox" name="page[]" value="<?php echo $page->getId() ?>">
						<?php echo $page->content_name
						?></label>
					<?php endforeach;
					?>
					<div class="alignleft" style="margin-top: 10px">
						<a class="page-check-all" href="#checkall">Check All</a>&nbsp;|&nbsp; <a class="page-uncheck-all" href="#uncheck">Uncheck All</a>
					</div>
					<div class="right">
						<img class="ajax-loader-widget" src="<?php echo $this->baseUrl() ?>/images/ajax_spin.gif"/>
						<input type="submit" class="add-page btn btn-primary" value="Add Item" />
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

<!-------------
---- MENUS ----
-------------->
<div id="custom-menus" class="span8">
	<div id="menu" class="portlet" style="margin-bottom: 10px;">
		<div class="portlet-header">
			<h4>Menu</h4>
		</div>
		<div class="portlet-inside">
			<div class="alert alert-info portlet-description">
				<p>
					<i class="icon-exclamation-sign"></i>
					To create a custom menu, choose items pages from the left column to add to this menu.
				</p>
				<p>
					After you have added your items, drag and drop to put them in the order you want.
				</p>
				<p>
					When you have finished building your custom menu, make sure you click the Save Menu button.
				</p>
			</div>
			<div class="portlet-form">
				<form action="" method="post" class="form-horizontal">
					<label class="control-label alignleft quarter">Menu Name</label>
					<input type="text" id="menu-name" class="half" name="menu-name"/>
					<div class="alignright">
						<img class="ajax-loader-widget" src="<?php echo $this->baseUrl() ?>/images/ajax_spin.gif"/>
						<input type="submit" class="add-menu btn btn-primary" value="Add Menu" />
					</div>
				</form>
			</div>

			<!------------------
			---- MENU LIST -----
			------------------->
			<div id="menus-list">
				<?php if( $menus ) :
				?>
				<?php foreach( $menus as $name => $menu ) : // MENU LIST
				?>
				<div id="<?php echo $name ?>" class="portlet">
					<div class="portlet-header">
						<h4><?php echo ucwords($menu['name'])
						?></h4>
						<div class="menu-save-top">
							<div class="control-group">
								<label class="control-label alignleft quarter">Menu Name</label>
								<input type="text" id="menu-name" name="menu-name" value="<?php echo $menu['name']; ?>" />
								<div class="alignright">
									<img class="ajax-loader-widget" src="<?php echo $this->baseUrl() ?>/images/ajax_spin.gif"/>
									<input name="submit"
									class="btn"
									type="submit" value="Save Menu" />
								</div>
							</div>
							<div class="control-group" style="margin-top: 10px">
								<a class="menu-remove" href="#remove">Delete Menu</a>&nbsp; &nbsp; <a class="menu-view" href="#view">View Menu</a>
							</div>
						</div>
					</div>
					<div class="portlet-inside hide">
						<div class="info <?php if( $menu['menus'] ) echo 'hide'; ?>">
							<div class="alert alert-info portlet-message">
								<i class="icon-exclamation-sign"></i>
								Select menu items (pages, links) from the boxes at left to begin building your custom menu
							</div>
						</div>
						<!------------------
						------- MENU -------
						------------------->
						<form action="#">
							<ol class="menu-sortable ui-sortable">
								<?php if( $menu['menus'] ) {
									echo $this->renderNestedSortable( $menu['menus'], $_pages );
								} ?>
							</ol>
							<div class="menu-save-bottom">
								<div class="alignleft">
									<a class="menu-close" href="#close">Close</a>
								</div>
								<div class="alignright <?php if( !$menu['menus'] ) echo 'hide'?>">
									<img class="ajax-loader-widget" src="<?php echo $this->baseUrl() ?>/images/ajax_spin.gif"/>
									<input name="submit"
									class="btn btn-primary"
									type="submit" value="Save Menu" />
								</div>
							</div>
						</form>
					</div>
				</div>
				<?php endforeach; // END LOOP MENU LIST
				?>
				<?php endif;
				?>
			</div>
		</div>
	</div>
</div>

