<!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
<div class="row fileupload-buttonbar" style="margin-left: 0">
	<div style="margin-bottom: 10px">
		<!-- The fileinput-button span is used to style the file input field as button -->
		<span class="btn btn-success fileinput-button">
			<i class="icon-plus icon-white"></i>
			<span>Add files...</span>
			<input type="file" name="files[]" multiple>
		</span>
		
		<button type="submit" class="btn btn-primary start">
			<i class="icon-upload icon-white"></i>
			<span>Start upload</span>
		</button>
		
		<button type="reset" class="btn btn-warning cancel">
			<i class="icon-ban-circle icon-white"></i>
		<span>Cancel upload</span>
		</button>
		
		<button type="button" class="btn btn-danger delete">
			<i class="icon-trash icon-white"></i>
			<span>Delete</span>
		</button>
		
		<input type="checkbox" class="toggle">
	</div>
	<div class="span5" style="margin-left:0;">
		<div class="progress progress-success progress-striped active fade">
			<div class="bar" style="width:0%;"></div>
		</div>
	</div>
</div>
<!-- The loading indicator is shown during image processing -->
<div class="fileupload-loading"></div> 

<br/>
<!-- The table listing the files available for upload/download -->
<table class="table table-striped" style="margin:0;">
	<tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery">
	</tbody>
</table>

<!-- show if empty -->
<div id="files-empty" class="alert alert-error half hide">
	<i class="icon-warning-sign"></i>
	<?php echo sprintf('Your %s images is empty', ucfirst($this->content)) ?>
</div>
		

<!-- modal-gallery is the modal dialog used for the image gallery -->
<div id="modal-gallery" class="modal modal-gallery hide fade">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">&times;</a>
        <h3 class="modal-title"></h3>
    </div>
    <div class="modal-body preview"><div class="modal-image"></div></div>
    <div class="modal-footer">
        <a class="btn btn-success" target="_blank" rel="insertimage" style="float:left;">
            <i class="icon-download"></i>
            <span>Set featured image</span>
        </a>
        <a class="btn modal-download" target="_blank">
            <i class="icon-download"></i>
            <span>Download</span>
        </a>
        <a class="btn btn-success modal-play modal-slideshow" data-slideshow="5000">
            <i class="icon-play icon-white"></i>
            <span>Slideshow</span>
        </a>
        <a class="btn btn-info modal-prev">
            <i class="icon-arrow-left icon-white"></i>
            <span>Previous</span>
        </a>
        <a class="btn btn-primary modal-next">
            <span>Next</span>
            <i class="icon-arrow-right icon-white"></i>
        </a>
    </div>
</div>

<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td class="preview"><span class="fade"></span></td>
        <td class="name"><span>{%=file.name%}</span></td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        {% if (file.error) { %}
            <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else if (o.files.valid && !i) { %}
            <td colspan="2">
                <div class="progress progress-success progress-striped active"><div class="bar" style="width:0%;"></div></div>
            </td>
            <td class="start">{% if (!o.options.autoUpload) { %}
                <button class="btn btn-primary">
                    <i class="icon-upload icon-white"></i>
                    <span>{%=locale.fileupload.start%}</span>
                </button>
            {% } %}</td>
        {% } else { %}
            <td colspan="2"></td>
        {% } %}
        <td class="cancel">{% if (!i) { %}
            <button class="btn btn-warning">
                <i class="icon-ban-circle icon-white"></i>
                <span>{%=locale.fileupload.cancel%}</span>
            </button>
		</td>
        {% } %}
    </tr>
{% } %}
</script>

<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        {% if (file.error) { %}
            <td class="error"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
            <td class="name"><span>{%=file.name%}</span></td>
            <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
            <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else { %}
            <td class="preview">{% if (file.url) { %}
                <a href="{%=file.url%}" title="View {%=file.name%}" rel="gallery" download="{%=file.name%}">
                	<img src="{%=file.url%}" style="max-width 100px; max-height: 100px">
                </a>
            {% } %}
            </td>
            <td class="name" style="vertical-align:middle">
                <a href="#" title="{%=file.name%}" rel="insertimage" download="{%=file.name%}">Set featured image</a>
                <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.url&&'gallery'%}" download="{%=file.name%}">View</a>	
            </td>
            <td class="size" colspan="2" style="vertical-align:middle"><span>{%=o.formatFileSize(file.size)%}</span></td>
            <td colspan="2"></td>
        {% } %}
        <td class="delete" style="vertical-align:middle">
            <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
                <i class="icon-trash icon-white"></i>
                <span>{%=locale.fileupload.destroy%}</span>
            </button>
            <input type="checkbox" name="delete" value="1">
        </td>
    </tr>
{% } %}
</script>
<?php
$this->jQuery()//->addJavascriptFile('http://blueimp.github.com/JavaScript-Templates/tmpl.min.js')
			   //->addJavascriptFile('http://blueimp.github.com/JavaScript-Load-Image/load-image.min.js')
			   //->addJavascriptFile('http://blueimp.github.com/JavaScript-Canvas-to-Blob/canvas-to-blob.min.js')
			   //->addJavascriptFile('http://blueimp.github.com/cdn/js/bootstrap.js')
			   //->addJavascriptFile('http://blueimp.github.com/Bootstrap-Image-Gallery/js/bootstrap-image-gallery.min.js')
			   ->addJavascriptFile($this->baseUrl().'/js/blueimp/tmpl.min.js')
			   ->addJavascriptFile($this->baseUrl().'/js/blueimp/load-image.min.js')
			   ->addJavascriptFile($this->baseUrl().'/js/blueimp/canvas-to-blob.min.js')
			   ->addJavascriptFile($this->baseUrl().'/js/blueimp/bootstrap.js')
			   ->addJavascriptFile($this->baseUrl().'/js/blueimp/bootstrap-image-gallery.min.js')
			   ->addJavascriptFile($this->baseUrl().'/js/blueimp/jquery.ui.widget.js')
			   ->addJavascriptFile($this->baseUrl().'/js/blueimp/jquery.iframe-transport.js')
			   ->addJavascriptFile($this->baseUrl().'/js/blueimp/jquery.fileupload.js')
			   ->addJavascriptFile($this->baseUrl().'/js/blueimp/jquery.fileupload-ip.js')
			   ->addJavascriptFile($this->baseUrl().'/js/blueimp/jquery.fileupload-ui.js')
			   ->addJavascriptFile($this->baseUrl().'/js/blueimp/jquery.fileupload-ui.js')
			   ->addJavascriptFile($this->baseUrl().'/js/blueimp/locale.js')
			   ->addJavascriptFile($this->baseUrl().'/js/blueimp/main.js');
?>