<?php if ($this->pageCount > 1) : ?>
	<tr>
		<td colspan="3">
			<ul class="pagination alignright">
				<!-- FIRST -->
				<li>
					<a class="btn" href="<?php echo $this->url( array( 
					'page' => $this->first ), $this->route); ?>">&laquo; first</a>
				</li>
		
				<!-- PREVIOUS -->
				<li>
					<a class="btn" href="<?php echo $this->url( array( 
					'page' => $this->previous ), $this->route); ?>">&lt; previous</a>
				</li>
				
				<!-- NUMBERS -->
				<?php foreach($this->pagesInRange as $page) : ?>
				<li>
					<a class="btn <?php if ($page == $this->current) : ?>btn-primary<?php endif; ?>" 
						href="<?php echo $this->url( array( 
						'page' => $page ), $this->route); ?>">
						<?php echo $page; ?>
					</a>
				</li>		
				<?php endforeach; ?>
				<!-- NEXT -->
				<li>
					<a class="btn" href="<?php echo $this->url( array( 'page' => $this->next ), $this->route); ?>">next &gt;</a>
				</li>
		
				<!-- LAST -->
				<li>
					<a class="btn" href="<?php echo $this->url( array( 'page' => $this->last ), $this->route); ?>">last &raquo;</a>
				</li>
				
			</ul>
		</td>
	</tr>
<?php endif; ?>
