<tr>
	<td>
	<input type="checkbox">
	</td>
	<td><?php echo ucwords($this -> name); ?></td>
	<td><?php echo ($this->status == 'L') ? 'Published' : 'Draft' ; ?></td>
	<td><?php echo $this->getDate( $this->date ); ?></td>
	<td>
	<ul class="actions">
		<li>
			<a class="view open-modal" href="#people-<?php echo $this->id; ?>" title="View <?php echo ucwords($this->name) ?>" rel="tooltip">view</a>
		</li>
		<li>
			<a class="edit" href="<?php echo $this->url( array( 'action' => 'edit', 'id' =>  $this->id))  ?>" title="Edit <?php echo $this->name ?>" rel="tooltip">edit</a>
		</li>
		<li>
			<a class="delete" onclick="if (! confirm('Are you sure ?')) { return false; }"
			href="<?php echo $this->url( array( 'action' => 'delete', 'id' =>  $this->id))  ?>" title="Delete <?php echo $this->name ?>" rel="tooltip">delete</a>
		</li>
	</ul></td>
</tr>

<article id="people-<?php echo $this->id; ?>" class="hide full-block nested">
	<div class="article-container">

		<header>
			<h2><?php echo ucwords($this->name); ?></h2>
		</header>

		<section>
			<h5><?php echo $this->getDate( $this->date ); ?></h5>
			<p><?php echo $this->description; ?></p>
		</section>
	</div>
</article>
		