<?php echo $this->docType(); ?>
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> 
<html lang="en" class="no-js"> <!--<![endif]-->
<head></head>
<body>

<div class="span6" style="margin: 10px;">
	<form id="fileupload" method="post" enctype="multipart/form-data" 
		  action="<?php echo $this->url(array(
			  "controller"=>"blueimp", 
			  "action"=>"index", 
			  "content" => "modal", 
			  "id" => $this->slideId
		  )) ?>">
		  
		<?php echo $this->partial('partials/blueimp-multiple-upload.phtml', array('content' => 'modal')) ?>
		
	</form>
</div>

	<!-- JS Libs at the end for faster loading -->
	<?php 
	// load jQuery
	$this->jQuery()->setLocalPath($this->baseUrl().'/js/jquery/jquery-1.7.1.min.js')
	 		 ->addStylesheet($this->baseUrl().'/css/blueimp/jquery.fileupload-ui.css')
		     ->addStylesheet($this->baseUrl().'/css/blueimp/bootstrap.min.css')
		     ->addStylesheet($this->baseUrl().'/css/blueimp/bootstrap-responsive.min.css')
		     ->addStylesheet($this->baseUrl().'/css/blueimp/bootstrap-image-gallery.min.css')
			 ->enable();
	echo $this->jQuery();
	?>
</body>
</html>
