<div class="txt">
	<h2 class="title">
		<a href="<?php echo $this->url( array('title' => $this->slug, 'isSingle' => true), 'news' ); ?>" 
		   title="<?php echo ucwords($this->name); ?>"> 
			<?php echo ucwords($this->name); ?> 
		</a>
	</h2>
	<div>
		<span><?php echo $this->getDate($this->date); ?></span>
	</div>
	
	<div style="margin-top:15px;">
	<?php 
	$link = '...<a href="'.$this->url( array('title' => $this->slug, 'isSingle' => true), 'news' ).'"
	title="read more">Read more</a>';
	?>
	
	<?php if( $this->image ) : ?>
		<div style="width:100px; float: left;">
		<img src="<?php echo $this->baseUrl() ?>/uploads/thumbnail/<?php echo $this->image; ?>" 
			 alt="Image <?php echo $this->name ?>" 
			 style="max-width:100px" />
		</div>
		<div style="width:800px; float: left; margin-left: 10px;">
		<?php echo $this->getExcerptContent( $this->description, $link ); ?>
		</div>
	<?php else : ?>
		<?php echo $this->getExcerptContent( $this->description, $link ); ?>
	<?php endif; ?>
	</div>
</div>